# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
   	before_all do
    	setup_circle_ci
  	end

	lane :beta do
		#get provisioning profile 
		match(
  			readonly: false,
  			type: 'adhoc',
  			app_identifier: 'com.github.mechinmaru.HelloWorldCI'
		)

		increment_build_number

		# build ipa
		gym(
			project:'HelloWorldCI.xcodeproj',
			scheme:'HelloWorldCI',
			clean:true,
			export_method: 'ad-hoc'
		)  

		#deliverly
		hockey(
			api_token: 'a57fb5426029489695dd5788a3fb00e1'
		)
	end

end